import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { randomUUID } from 'node:crypto';
import type { PGlite } from '@electric-sql/pglite';
import { asUser,testDatabase } from './helpers/database.js';

let db:PGlite; const clientA=randomUUID(),clientB=randomUUID();
beforeAll(async()=>{db=await testDatabase();await db.query("insert into auth.users(id,email,raw_user_meta_data) values($1,'a@example.test',$3),($2,'b@example.test',$4)",[clientA,clientB,JSON.stringify({display_name:'A'}),JSON.stringify({display_name:'B'})])});
afterAll(async()=>db?.close());
describe('Supabase account and instance isolation',()=>{
  it('provisions client profiles, limits and one default agent atomically',async()=>{for(const user of [clientA,clientB]){const p=await db.query<{role:string;status:string;default_organization_id:string}>('select role,status,default_organization_id from public.profiles where user_id=$1',[user]);expect(p.rows[0]).toMatchObject({role:'client',status:'active'});expect((await db.query('select id from public.ai_agents where owner_user_id=$1 and is_default',[user])).rows).toHaveLength(1);expect((await db.query<{max_agents:number}>('select max_agents from public.account_limits where owner_user_id=$1',[user])).rows[0]?.max_agents).toBe(2)}});
  it('enforces the two-agent quota in the database',async()=>{await asUser(db,clientA,()=>db.query("select id from public.create_agent_for_current_user('Extra',null,'openai','gpt-4.1-mini','', '{}'::jsonb, '{}'::jsonb)"));await expect(asUser(db,clientA,()=>db.query("select id from public.create_agent_for_current_user('Third',null,'openai','gpt-4.1-mini','', '{}'::jsonb, '{}'::jsonb)"))).rejects.toThrow('limit');expect((await db.query("select id from public.ai_agents where owner_user_id=$1 and status='active'",[clientA])).rows).toHaveLength(2)});
  it('prevents assigning another login agent and hides its connections through RLS',async()=>{const orgA=(await db.query<{default_organization_id:string}>('select default_organization_id from public.profiles where user_id=$1',[clientA])).rows[0]!.default_organization_id;const agentA=(await db.query<{id:string}>('select id from public.ai_agents where owner_user_id=$1 and is_default',[clientA])).rows[0]!.id;const agentB=(await db.query<{id:string}>('select id from public.ai_agents where owner_user_id=$1 and is_default',[clientB])).rows[0]!.id;const connection=randomUUID();await db.query("insert into public.connections(id,organization_id,owner_user_id,agent_id,name,provider) values($1,$2,$3,$4,'A1','evolution')",[connection,orgA,clientA,agentA]);await expect(asUser(db,clientA,()=>db.query('select * from public.assign_agent_to_connection($1,$2)',[connection,agentB]))).rejects.toThrow('not found');await asUser(db,clientB,async()=>expect((await db.query('select id from public.connections where id=$1',[connection])).rows).toEqual([]))});
});
